monolog:
    channels: [connect,api]
    handlers:
        applog:
            type:           rotating_file
            max_files:      3
            path: "%kernel.logs_dir%/%kernel.environment%.all.log"
            level: info
        login:
            type:           rotating_file
            max_files:      365
            path:           "%kernel.logs_dir%/%kernel.environment%.auth.log"
            level:          info
            channels:       [security]
        connect:
            type:           rotating_file
            max_files:      365
            path:           "%kernel.logs_dir%/%kernel.environment%.connect.log"
            level:          info
            channels:       [connect]
        api:
            type:           rotating_file
            max_files:      365
            path:           "%kernel.logs_dir%/%kernel.environment%.api.log"
            level:          info
            channels:       [api]
        main_error:
            type:           fingers_crossed
            action_level:   error
            handler:        streamed_error
        streamed_error:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.error.log"
            level:          info
        streamed_critical:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.critical.log"
            level:          info
