controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /
    name_prefix: app_
api_controllers:
    resource: '../../src/Controller/Api'
    type: annotation
    prefix: /api
    name_prefix: api_
kernel:
    resource: ../../src/Kernel.php
    type: annotation
