#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_authentication:
  path: /api/login
gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
